// vue-examples/src/views/Stocks/components/Symbol.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import type { Direction } from '../types';
import { directionIndicators, formatPrice, getDirection } from '../utils';
import YahooFinance, { type Stock } from '../YahooFinance';

const latest = ref<Stock | undefined>(undefined);
const direction = ref<Direction>('none');

const { symbol } = defineProps<{
  symbol: string;
}>();

const onUpdate = (update: Stock) => {
  if (update.price === latest.value?.price) return;
  if (latest.value) {
    direction.value = getDirection(update.price - latest.value.price);
  }
  latest.value = update;
};

onMounted(() => {
  YahooFinance.subscribe([symbol], onUpdate);
});

onUnmounted(() => {
  YahooFinance.unsubscribe([symbol], onUpdate);
});
</script>

<template>
  <span>
    {{ symbol }} |
    <span v-if="latest" class="price" :class="direction">
      {{ directionIndicators[direction] }}
      {{ formatPrice(latest.price) }}
    </span>
    <span v-else class="price"> Loading... </span>
  </span>
</template>

// react-examples/src/pages/Stocks/components/Symbol.tsx
import { useCallback, useEffect, useState } from 'react';
import { Direction } from '../types';
import { directionIndicators, formatPrice, getDirection } from '../utils';
import YahooFinance, { Stock } from '../YahooFinance';

export type SymbolProps = {
  symbol: string;
};

export default function Symbol({ symbol }: SymbolProps) {
  const [latest, setLatest] = useState<Stock | null>(null);
  const [direction, setDirection] = useState<Direction>('none');

  const onUpdate = useCallback((update: Stock) => {
    setLatest((current) => {
      if (update.price === current?.price) return current;
      if (current) {
        const newDirection = getDirection(update.price - current.price);
        setDirection(newDirection);
      }
      return update;
    });
  }, []);

  useEffect(() => {
    YahooFinance.subscribe([symbol], onUpdate);
    return () => {
      YahooFinance.unsubscribe([symbol], onUpdate);
    };
  }, [symbol, onUpdate]);

  return (
    <span>
      {symbol} |{' '}
      {latest ? (
        <span className={`price ${direction}`}>
          {directionIndicators[direction]}
          {formatPrice(latest.price)}
        </span>
      ) : (
        <span className="price">Loading...</span>
      )}
    </span>
  );
}
