// vue-examples/src/views/Shop-pinia/components/Product.vue
<script setup lang="ts">
import { ref } from 'vue';
import { type ProductInfo, type Size, sizes } from '../types';
import { useCartStore } from '../stores/cart';

defineProps<{
  product: ProductInfo;
}>();

const quantity = ref(1);
const size = ref<Size>('S');
const { addToCart } = useCartStore();
</script>
<template>
  <article>
    <header>{{ product.title }}</header>
    <div class="grid">
      <img :alt="product.title" :src="product.image" />
      <div>
        <p>${{ product.price.toFixed(2) }} USD</p>
        <label v-if="product.hasSize">
          Size
          <select v-model="size">
            <option v-for="item in sizes" :key="item" :value="item">
              {{ item }}
            </option>
          </select>
        </label>
        <label>
          Quantity
          <input v-model.number="quantity" type="number" min="1" />
        </label>
        <p>{{ product.description }}</p>
        <div class="end">
          <button @click="addToCart(product, size, quantity)">
            Add to Cart
          </button>
        </div>
      </div>
    </div>
  </article>
</template>

// react-examples/src/pages/Shop-zustand/components/Product.tsx
import { useState } from 'react';
import { ProductInfo, Size, sizes } from '../types';
import { useCartStore } from '../stores/cart';

export type ProductProps = {
  product: ProductInfo;
};

function Product({ product }: ProductProps) {
  const [quantity, setQuantity] = useState(1);
  const [size, setSize] = useState<Size>('S');
  const addToCart = useCartStore((store) => store.addToCart);
  return (
    <article>
      <header>{product.title}</header>
      <div className="grid">
        <img alt={product.title} src={product.image} />
        <div>
          <p>${product.price.toFixed(2)} USD</p>
          {product.hasSize && (
            <label>
              Size
              <select
                value={size}
                onChange={(e) => setSize(e.target.value as Size)}
              >
                {sizes.map((item) => (
                  <option key={item} value={item}>
                    {item}
                  </option>
                ))}
              </select>
            </label>
          )}
          <label>
            Quantity
            <input
              value={quantity}
              onChange={(e) => setQuantity(Number(e.target.value))}
              type="number"
              min="1"
            />
          </label>
          <p>{product.description}</p>
          <div className="end">
            <button
              type="button"
              onClick={() => addToCart(product, size, quantity)}
            >
              Add to Cart
            </button>
          </div>
        </div>
      </div>
    </article>
  );
}

export default Product;
